feat: merge sch() to main branch
ShineSoYoung/CRA pull request #11
Opened 2022-03-31 08:09 UTC by BulgogiBake

sch의 rough 코드를 main branch로 Pull Request 합니다

2022-03-31 08:23 UTC, ShineSoYoung approved these changes
sch기능 구현 확인하였습니다!

2022-03-31 15:11 UTC, octorbirth approved these changes

2022-03-31 15:11 UTC, octorbirth commented on E-Project/E-Project/sch.cpp
> +	int idx = 0;
사용하지 않는 변수인 것 같네요 나중에 리팩토링할 때 제거 하면 좋을것 같아요

2022-03-31 15:11 UTC, octorbirth commented on E-Project/E-Project/sch.cpp
> +		}
저는 이 부분 map 부분으로 해서 구현했어요ㅎㅎ

2022-03-31 15:11 UTC, octorbirth commented on E-Project/E-Project/sch.cpp
> +				break;
저도 이 부분 고민하고 있는데 resultCnt++ 되는 것이 중복되는 곳이 많아서,, 
디자인 패턴 적용하고 싶은데 뭘 어떻게 할지 모르겠네요

2022-03-31 15:11 UTC, octorbirth commented on E-Project/E-Project/sch.cpp
> +	return result;
결과 값 처리 방식에서 문자열 활용하는게 좋네요 ㅎ

2022-04-01 00:35 UTC, momohari approved these changes

2022-04-01 01:04 UTC, momohari requested changes
conflict로 인한 빌드 에러가 있습니다.

2022-04-01 02:25 UTC, BulgogiBake commented on E-Project/E-Project/sch.cpp
> +				break;
맞아요. 이 부분은 고민이 좀 필요하겠네요.

2022-04-01 02:25 UTC, BulgogiBake commented on E-Project/E-Project/sch.cpp
> +		}
map 부분 구현 참고 후에 적용해보겠습니다

2022-04-01 02:25 UTC, BulgogiBake commented on E-Project/E-Project/sch.cpp
> +	int idx = 0;
제거했습니다.

2022-04-01 03:29 UTC, BulgogiBake commented
conflict 이 많이 꼬여서 feature/merge-sch-function 으로 branch 이동하겠습니다.

2022-04-01 03:29 UTC, closed without merging